function force = frstatic(p,p0,v,gamma,cos_theta,rou)
%   This function is used to calculate the force generated by the static repulsion field
if(cos_theta<0)
    force=double( gamma*(cos_theta^2)/(rou^3)*norm(v)*(p-p0));
else
    force=[0 0 0];
end
end

